name: Testing

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    container: archlinux:base-devel
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: bash ./.ci/install.sh

    - name: Configure
      run: cmake -B build -S .

    - name: Build
      run: cmake --build build
